version: "3.8"
services:
  pg:
    image: postgres
    command: postgres -c 'max_connections=500'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: $project_name_cabab_case$-dev
    restart: always
    volumes:
      - "./dump:/dump"
      - "./seeds:/seeds"
